stages:
  - test
  - push

variables:
  IMAGE: $DOCKER_REGISTRY/$DOCKER_REGISTRY_USER/$CI_PROJECT_NAME

before_script:
  - docker login --username $DOCKER_REGISTRY_USER --password $DOCKER_REGISTRY_PASS $DOCKER_REGISTRY

test:
  stage: test
  image: node:10-alpine
  script:
    - export CI=true
    - yarn
    - yarn test
  tags:
    - run_docker

build:
  stage: push
  script:
    - CONTAINER_IMAGE="${IMAGE}:${CI_COMMIT_REF_SLUG}"
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
  tags:
    - build_docker
  only:
    - branches
  except:
    - /^v\d+\.\d+\.\d+$/
    
build-latest:
  stage: push
  script:
    - echo "This is master"
  tags:
    - build_docker
  only:
    refs:
      - master

build-tag:
  stage: push
  script:
    - CONTAINER_TAG_IMAGE="${IMAGE}:${CI_COMMIT_TAG//v/}"
    - CONTAINER_LATEST_IMAGE="${IMAGE}:latest"
    - docker build --pull -t $CONTAINER_LATEST_IMAGE .
    - docker tag $CONTAINER_LATEST_IMAGE $CONTAINER_TAG_IMAGE
    - docker push $CONTAINER_LATEST_IMAGE
    - docker push $CONTAINER_TAG_IMAGE
  tags:
    - build_docker
  only:
    - /^v\d+\.\d+\.\d+$/
  except:
    - branches